### ISSUE TITLE
Invalid authentication request: The response type is not supported.

### ISSUE THREAD

**Issue by jeeppeck** [docusign/eg-03-node-auth-code-grant#13]
While trying to test authentication flow using the "Send an envelope with a remote (email) signer and cc recipient" option, after being redirected to the DocuSign login page I immediately get the message:

"Invalid authentication request: The response type is not supported."

And then continue to receive the message after entering my username and password.

![image](https://user-images.githubusercontent.com/9276448/80320641-a7298c80-87e5-11ea-80d7-ebcdac6031a4.png)

**Comment by LarryKlugerDS** [comment]
Please check that your integration key is set for Authorization Code grant. 
See the screenshot of how the integration key should be set:
<img width="480" alt="Screen Shot 2020-04-27 at 9 32 42 AM" src="https://user-images.githubusercontent.com/13013082/80340937-39737400-886a-11ea-9b56-e0da53000cc8.png">
