### ISSUE TITLE
This account is not enabled for Smart Sections

### ISSUE THREAD

**Issue by 0xSharlie** [docusign/eg-03-node-auth-code-grant#7]
I'm attempting to create a responsive signing envelope using the htmlDefinition property in a document. I receive an error message: 

PLAN_ITEM_NOT_ENABLED: A requested plan item is not enabled for this account. This account is not enabled for Smart Sections.

**Comment by LarryKlugerDS** [comment]
Hi, To solve this issue, please send an email to go-live@docusign.com and ask them to add "Responsive Signing" and "Smart Sections" to your developer account. And be sure to include your account number.

Thanks,
Larry

**Comment by InbarGazit** [comment]
or you can create a new sandbox account as this is now available for all new demo accounts - https://www.docusign.com/blog/dsdev-smart-sections-developer-sandbox/
